
import React, { useState } from 'react';
import { FocusState, AIInsight, ProjectPlan } from '../types';

interface RightPanelIntelligenceProps {
  focus: FocusState;
  insight: AIInsight | null;
  loading: boolean;
  onBudgetUpdate: (leadId: string) => void;
  onApprovePlan: () => void;
  onRevisePlan?: () => void;
}

const RightPanelIntelligence: React.FC<RightPanelIntelligenceProps> = ({ 
  focus, insight, loading, onBudgetUpdate, onApprovePlan, onRevisePlan 
}) => {
  const [showThinking, setShowThinking] = useState(false);
  const [selectedMilestones, setSelectedMilestones] = useState<number[]>([]);

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-4 w-24 bg-gray-50 rounded animate-pulse" />
        <div className="h-32 bg-gray-50 rounded animate-pulse" />
      </div>
    );
  }

  const isContact = focus.type === 'contact';
  const plan: ProjectPlan | undefined = focus.data?.proposedPlan;

  const toggleMilestone = (index: number) => {
    setSelectedMilestones(prev => 
      prev.includes(index) ? prev.filter(i => i !== index) : [...prev, index]
    );
  };

  return (
    <div className="animate-in fade-in duration-300 space-y-10">
      {/* 4-Week Plan Display */}
      {plan ? (
        <section className="animate-in slide-in-from-bottom-4 duration-500">
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] text-gray-400 font-bold mb-1">Proposed 4-Week Plan</h3>
            <p className="text-[12px] text-gray-400 font-serif italic">Generated by Planner Agent from market intelligence.</p>
          </div>

          <div className="space-y-1 mb-10">
            {plan.milestones.map((m, i) => (
              <div 
                key={i} 
                className="group flex items-center py-4 px-2 border-b border-gray-50 last:border-0 hover:bg-gray-50 transition-colors cursor-pointer"
                onClick={() => toggleMilestone(i)}
              >
                <div className={`w-4 h-4 rounded border flex items-center justify-center mr-4 transition-all ${selectedMilestones.includes(i) || selectedMilestones.length === 0 ? 'bg-black border-black' : 'border-gray-200'}`}>
                  {(selectedMilestones.includes(i) || selectedMilestones.length === 0) && <span className="text-[10px] text-white font-bold">✓</span>}
                </div>
                <div className="flex-1">
                  <div className="flex items-center space-x-2 mb-0.5">
                    <span className="text-[11px] font-bold text-gray-400 uppercase tracking-tighter">{m.week}</span>
                    <h4 className="text-[14px] font-medium text-gray-900">{m.title}</h4>
                  </div>
                  <p className="text-[12px] text-gray-400 font-serif italic line-clamp-1">{m.description}</p>
                </div>
                <span className={`text-[9px] uppercase tracking-widest px-2 py-0.5 rounded font-bold ml-4 ${
                  m.effort === 'High' ? 'bg-red-50 text-red-500' : 'bg-gray-100 text-gray-500'
                }`}>
                  {m.effort}
                </span>
              </div>
            ))}
          </div>

          <div className="space-y-3 mb-10">
             <button 
               onClick={onApprovePlan}
               className="w-full py-4 bg-black text-white rounded-xl text-[11px] uppercase font-bold tracking-widest hover:bg-gray-800 transition-all shadow-lg active:scale-95"
             >
               Approve Plan & Create Tasks
             </button>
             <button 
               onClick={() => alert("Revise functionality: This would trigger the Planner Agent with new constraints.")}
               className="w-full py-4 bg-white border border-gray-200 text-gray-500 rounded-xl text-[11px] uppercase font-bold tracking-widest hover:bg-gray-50 transition-all"
             >
               Revise with Agent
             </button>
          </div>

          {/* AI Explanation Sidebar (Integrated in Right Panel) */}
          <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 space-y-6">
             <div>
               <h4 className="text-[10px] uppercase font-bold text-gray-400 mb-3">Why this plan</h4>
               <p className="text-[12px] text-gray-600 font-serif italic leading-relaxed">
                 {plan.reasoning}
               </p>
             </div>
             
             <div>
               <h4 className="text-[10px] uppercase font-bold text-gray-400 mb-2">Dependencies</h4>
               <ul className="text-[11px] text-gray-500 space-y-1">
                 {plan.dependencies.map((d, i) => <li key={i}>• {d}</li>)}
               </ul>
             </div>

             <div>
               <h4 className="text-[10px] uppercase font-bold text-gray-400 mb-2">Assumptions</h4>
               <ul className="text-[11px] text-gray-500 space-y-1">
                 {plan.assumptions.map((a, i) => <li key={i}>• {a}</li>)}
               </ul>
             </div>
          </div>
        </section>
      ) : (
        <>
          {isContact && focus.data && !focus.data.budgetAnalysis && (
            <button 
              onClick={() => onBudgetUpdate(focus.data.id)}
              disabled={focus.data.isCalculating}
              className="w-full py-3 bg-emerald-50 border border-emerald-100 text-emerald-700 text-[10px] uppercase font-bold tracking-widest rounded-xl hover:bg-emerald-100 transition-all flex items-center justify-center space-x-2"
            >
              {focus.data.isCalculating ? 'Executing Code...' : '📊 Run ROI Projections'}
            </button>
          )}

          {focus.data?.budgetAnalysis && (
            <section className="bg-emerald-50/50 border border-emerald-100 p-6 rounded-2xl animate-in zoom-in duration-300">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-[10px] uppercase tracking-widest text-emerald-600 font-bold">Budget Validated</h3>
                <span className="text-[8px] bg-emerald-600 text-white px-1.5 py-0.5 rounded font-bold">CODE EXEC</span>
              </div>
              <div className="flex justify-between items-end mb-4">
                <div>
                  <span className="text-[9px] uppercase font-bold text-gray-400 block mb-1">Est. Cost</span>
                  <span className="text-xl font-serif text-gray-800">${focus.data.budgetAnalysis.totalEstimatedCost.toLocaleString()}</span>
                </div>
                <div className="text-right">
                  <span className="text-[9px] uppercase font-bold text-gray-400 block mb-1">ROI (12m)</span>
                  <span className="text-xl font-serif text-emerald-600">{focus.data.budgetAnalysis.roiProjection}%</span>
                </div>
              </div>
              <p className="text-[11px] text-gray-600 font-serif italic leading-relaxed">
                {focus.data.budgetAnalysis.reasoning}
              </p>
            </section>
          )}

          {insight?.reasoningTrace && (
            <section className="bg-gray-50 border border-gray-100 p-4 rounded-xl transition-all">
              <button 
                onClick={() => setShowThinking(!showThinking)}
                className="flex justify-between items-center w-full mb-1"
              >
                <h3 className="text-[9px] uppercase tracking-widest text-gray-400 font-bold">AI Strategy Logic</h3>
                <span className="text-[9px] text-gray-300 font-bold">{showThinking ? 'Hide' : 'Expand Path'}</span>
              </button>
              <div className={`overflow-hidden transition-all duration-500 ${showThinking ? 'max-h-96 mt-3 opacity-100' : 'max-h-0 opacity-0'}`}>
                <p className="text-[11px] text-gray-500 font-serif italic leading-relaxed">
                  "{insight.reasoningTrace}"
                </p>
              </div>
            </section>
          )}

          <section>
            <h3 className="text-[10px] uppercase tracking-widest text-gray-400 font-bold mb-4">Strategic Insight</h3>
            <p className="text-[14px] leading-relaxed text-gray-600 font-serif italic">{insight?.summary}</p>
          </section>
        </>
      )}
    </div>
  );
};

export default RightPanelIntelligence;
